config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('https://liveteam.org/')

  get '/go/:id', to: 'links#destination', as: 'link_destination'
  resources :links, only: [:show, :new, :create]
end

app/models/link.rb
class Link
  include Mongoid::Document
  include Mongoid::Slug

  # Embed data
  field :name, type: String
  field :description, type: String
  field :image_url, type: String

  # Reddit thread ID
  field :thread_id, type: String

  # Shortened link
  field :link, type: String
  slug :link

  def url
    "https://reddit.com/live/#{thread_id}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
require 'mini_magick'
require 'uri'

class LinksController < ApplicationController

  before_action :get_link, only: [:destination, :show]

  def create
    new_url = LinksController.process_image(link_params)
    @link = Link.new(link_params)
    @link.image_url = new_url
    @link.save!
    redirect_to link_path(@link)
  end

  def self.process_image(params)
    filename = URI.parse(params[:image_url]).path.split('/').last
    template = MiniMagick::Image.open(Rails.root.join('app', 'assets', 'images', 'VLT-template.png'))
    base = MiniMagick::Image.open(params[:image_url])

    base.resize('1200x630')

    result = base.composite(template) do |c|
      c.compose "over"
      c.gravity "SouthWest"
    end
    result.write(Rails.root.join('public', 'images', filename)) # TODO upload to S3 here

    '/images/' + filename
  end

  def new
    @link = Link.new
  end

  def destination
  end

  def show
  end

  private
  def get_link
    @link = Link.find(params[:id])    
  end

  def link_params
    params.require(:link).permit!
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Click
    - if content_for? :meta
      = yield :meta
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/links/destination.html.haml
- content_for :meta do
  -# Redirect for users
  %meta{'http-equiv': 'refresh', 'content': "0; url=#{@link.url}"}

  -# Facebook/Open Graph
  %meta{property: 'og:title', content: @link.name}
  %meta{property: 'og:description', content: @link.description}
  %meta{property: 'og:image', content: @link.image_url}
  %meta{property: 'og:type', content: 'article'}
  %meta{property: 'og:site_name', content: 'Volunteer Live Team'}

  -# Twitter Cards
  %meta{property: 'twitter:card', content: 'summary_large_image'}
  %meta{property: 'twitter:title', content: @link.name}
  %meta{property: 'twitter:description', content: @link.description}
  %meta{property: 'twitter:image', content: @link.image_url}
  %meta{property: 'twitter:site', content: '@VLiveTeam'}

app/views/links/new.html.haml
= form_for @link do |f|
  = f.label :name
  = f.text_field :name, placeholder: "Name"

  = f.label :description
  = f.text_field :description, placeholder: "Short Description"

  = f.label :image_url
  = f.text_field :image_url, placeholder: "Image URL"

  = f.label :thread_id
  = f.text_field :thread_id, placeholder: "Reddit Thread ID"

  = f.label :link
  = f.text_field :link, placeholder: "Short Link"

  = f.submit "Create Link"

app/views/links/show.html.haml
%h1= @link.name
%h2= @link.description
%pre= link_destination_url(@link)